### ISSUE TITLE
Debugging HC kernels possible?

### ISSUE THREAD

**Issue by kyflores** [RadeonOpenCompute/ROCm-Debugger#6]
I noticed it says it isn't possible yet to debug hcc-lc kernels; does that imply that it is possible to debug hcc-hsail built HC kernels, such as those in `parallel_for_each` blocks? 

If so what compiler options need to be set? I can't tell if `rocm-gdb-debug-flags.sh`is for HC programs, and it also appears to have disappeared in master, but is still viewable of course in other branches.

Thank you very much!

**Comment by perhaad** [comment]
Hello, 

ROCm-gdb provides support for debugging hcc programs compiled with the hcc-hsail compiler. It allows debugging at the HSAIL level. 

The script was provided to simply set all the env variables needed to compile for debug and was only relevant to hcc-hsail. It was removed since hcc-hsail is no longer present in the rocm 1.4 package. 

If you are using hcc-hsail, you can find the script in one of the older release branches.

Thanks,
Perhaad
